go:
  lint: true
php:
  lint: true
java: 
  lint: true
  config: # google_checks.xml (default) | sun_checks.xml 
scala:
  lint: true
shell:
  lint: true
css:
  lint: true
js: 
  lint: jshint # jshint (default) | eslint | false
  config: .jshintrc